name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Build
        run: CI= npm run build
      - name: Purge old files
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ${{ secrets.PURGE_CMD }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.SSH_KEY}}
          port: ${{ secrets.PORT }}
      - name: ssh key with passphrase
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          source: "build/*"
          target: ${{ secrets.TARGET_DIR }}
